export type GroupSize = 'sm' | 'md' | 'lg';
export declare const sizeConfig: {
    readonly sm: {
        readonly text: "text-xs";
        readonly badgeText: "text-[10px]";
        readonly iconSm: "h-3 w-3";
        readonly icon: "h-3.5 w-3.5";
        readonly gap: "gap-1.5";
        readonly headerPy: "py-1.5";
        readonly tabPx: "px-3";
        readonly tabPy: "py-2";
        readonly badgePx: "px-1.5";
        readonly badgePy: "py-0.5";
        readonly contentPt: "pt-1";
        readonly contentPb: "pb-3";
        readonly contentPadding: "p-3";
        readonly indent: "pl-4";
        readonly sidebarMinW: "min-w-[120px]";
    };
    readonly md: {
        readonly text: "text-sm";
        readonly badgeText: "text-xs";
        readonly iconSm: "h-4 w-4";
        readonly icon: "h-4 w-4";
        readonly gap: "gap-2";
        readonly headerPy: "py-2";
        readonly tabPx: "px-4";
        readonly tabPy: "py-2.5";
        readonly badgePx: "px-2";
        readonly badgePy: "py-0.5";
        readonly contentPt: "pt-2";
        readonly contentPb: "pb-4";
        readonly contentPadding: "p-4";
        readonly indent: "pl-5";
        readonly sidebarMinW: "min-w-[140px]";
    };
    readonly lg: {
        readonly text: "text-base";
        readonly badgeText: "text-sm";
        readonly iconSm: "h-5 w-5";
        readonly icon: "h-5 w-5";
        readonly gap: "gap-2.5";
        readonly headerPy: "py-2.5";
        readonly tabPx: "px-5";
        readonly tabPy: "py-3";
        readonly badgePx: "px-2.5";
        readonly badgePy: "py-1";
        readonly contentPt: "pt-3";
        readonly contentPb: "pb-5";
        readonly contentPadding: "p-5";
        readonly indent: "pl-6";
        readonly sidebarMinW: "min-w-[160px]";
    };
};
