export type GroupSize = 'sm' | 'md' | 'lg';

export const sizeConfig = {
    sm: {
        text: 'text-xs',
        badgeText: 'text-[10px]',
        iconSm: 'h-3 w-3',
        icon: 'h-3.5 w-3.5',
        gap: 'gap-1.5',
        headerPy: 'py-1.5',
        tabPx: 'px-3',
        tabPy: 'py-2',
        badgePx: 'px-1.5',
        badgePy: 'py-0.5',
        contentPt: 'pt-1',
        contentPb: 'pb-3',
        contentPadding: 'p-3',
        indent: 'pl-4',
        sidebarMinW: 'min-w-[120px]',
    },
    md: {
        text: 'text-sm',
        badgeText: 'text-xs',
        iconSm: 'h-4 w-4',
        icon: 'h-4 w-4',
        gap: 'gap-2',
        headerPy: 'py-2',
        tabPx: 'px-4',
        tabPy: 'py-2.5',
        badgePx: 'px-2',
        badgePy: 'py-0.5',
        contentPt: 'pt-2',
        contentPb: 'pb-4',
        contentPadding: 'p-4',
        indent: 'pl-5',
        sidebarMinW: 'min-w-[140px]',
    },
    lg: {
        text: 'text-base',
        badgeText: 'text-sm',
        iconSm: 'h-5 w-5',
        icon: 'h-5 w-5',
        gap: 'gap-2.5',
        headerPy: 'py-2.5',
        tabPx: 'px-5',
        tabPy: 'py-3',
        badgePx: 'px-2.5',
        badgePy: 'py-1',
        contentPt: 'pt-3',
        contentPb: 'pb-5',
        contentPadding: 'p-5',
        indent: 'pl-6',
        sidebarMinW: 'min-w-[160px]',
    },
} as const;
